export interface Product {
  id: string
  name: string
  description: string
  originalPrice: number
  discountedPrice: number
  discountPercentage: number
  category: "makanan-jadi" | "bahan-makanan"
  status: "layak-konsumsi" | "untuk-ternak"
  stock: number
  expiryDate: string
  productionDate: string
  weight?: number
  image: string
  store: Store
  foodWasteSaved: number
}

export interface Store {
  id: string
  name: string
  location: string
  distance: string
  rating: number
  image: string
}

export const stores: Store[] = [
  {
    id: "store-1",
    name: "Bakery Citra",
    location: "Jl. Sudirman No. 45, Jakarta Pusat",
    distance: "1.2 km",
    rating: 4.8,
    image: "/bakery-logo.png",
  },
  {
    id: "store-2",
    name: "Restoran Padang Sederhana",
    location: "Jl. Gatot Subroto No. 12, Jakarta Selatan",
    distance: "2.5 km",
    rating: 4.6,
    image: "/restaurant-logo.png",
  },
  {
    id: "store-3",
    name: "Supermarket Fresh",
    location: "Jl. Thamrin No. 88, Jakarta Pusat",
    distance: "0.8 km",
    rating: 4.5,
    image: "/generic-supermarket-logo.png",
  },
  {
    id: "store-4",
    name: "Toko Sayur Makmur",
    location: "Pasar Minggu, Jakarta Selatan",
    distance: "3.1 km",
    rating: 4.3,
    image: "/vegetable-store-logo.jpg",
  },
]

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Roti Tawar Gandum Premium",
    description: "Roti tawar gandum segar dengan tekstur lembut, cocok untuk sarapan sehat",
    originalPrice: 25000,
    discountedPrice: 12500,
    discountPercentage: 50,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 15,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-13",
    weight: 500,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.5,
  },
  {
    id: "prod-2",
    name: "Croissant Butter Original",
    description: "Croissant butter dengan lapisan renyah dan lembut di dalam",
    originalPrice: 15000,
    discountedPrice: 7500,
    discountPercentage: 50,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 8,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-14",
    weight: 100,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.1,
  },
  {
    id: "prod-3",
    name: "Nasi Padang Komplit",
    description: "Nasi putih dengan rendang, ayam goreng, sambal hijau, dan sayur",
    originalPrice: 45000,
    discountedPrice: 22500,
    discountPercentage: 50,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 12,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-14",
    weight: 600,
    image: "/placeholder.svg",
    store: stores[1],
    foodWasteSaved: 0.6,
  },
  {
    id: "prod-4",
    name: "Ayam Rendang Bumbu Minang",
    description: "Rendang ayam dengan bumbu rempah khas Padang yang kaya rasa",
    originalPrice: 35000,
    discountedPrice: 14000,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 6,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-13",
    weight: 400,
    image: "/placeholder.svg",
    store: stores[1],
    foodWasteSaved: 0.4,
  },
  {
    id: "prod-5",
    name: "Sayur Bayam Segar",
    description: "Bayam hijau segar langsung dari petani lokal",
    originalPrice: 10000,
    discountedPrice: 5000,
    discountPercentage: 50,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 20,
    expiryDate: "2025-12-17",
    productionDate: "2025-12-14",
    weight: 250,
    image: "/placeholder.svg",
    store: stores[2],
    foodWasteSaved: 0.25,
  },
  {
    id: "prod-6",
    name: "Tomat Merah Segar",
    description: "Tomat merah berkualitas tinggi, sedikit memar namun layak konsumsi",
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercentage: 50,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 25,
    expiryDate: "2025-12-18",
    productionDate: "2025-12-13",
    weight: 500,
    image: "/placeholder.svg",
    store: stores[2],
    foodWasteSaved: 0.5,
  },
  {
    id: "prod-7",
    name: "Kue Bolu Pandan",
    description: "Kue bolu pandan lembut dengan aroma pandan yang harum",
    originalPrice: 30000,
    discountedPrice: 12000,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 5,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-12",
    weight: 300,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.3,
  },
  {
    id: "prod-8",
    name: "Donat Coklat Mini",
    description: "Donat mini dengan taburan coklat, sisa produksi hari ini",
    originalPrice: 20000,
    discountedPrice: 8000,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 10,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-14",
    weight: 200,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.2,
  },
  {
    id: "prod-9",
    name: "Pisang Cavendish",
    description: "Pisang cavendish matang sempurna dengan sedikit bercak hitam",
    originalPrice: 25000,
    discountedPrice: 10000,
    discountPercentage: 60,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 18,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-10",
    weight: 1000,
    image: "/placeholder.svg",
    store: stores[2],
    foodWasteSaved: 1.0,
  },
  {
    id: "prod-10",
    name: "Wortel Organik",
    description: "Wortel organik segar dengan bentuk tidak sempurna namun berkualitas",
    originalPrice: 15000,
    discountedPrice: 6000,
    discountPercentage: 60,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 30,
    expiryDate: "2025-12-20",
    productionDate: "2025-12-12",
    weight: 500,
    image: "/placeholder.svg",
    store: stores[3],
    foodWasteSaved: 0.5,
  },
  {
    id: "prod-11",
    name: "Kentang Merah",
    description: "Kentang merah ukuran kecil-sedang, cocok untuk direbus atau digoreng",
    originalPrice: 20000,
    discountedPrice: 8000,
    discountPercentage: 60,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 22,
    expiryDate: "2025-12-25",
    productionDate: "2025-12-10",
    weight: 1000,
    image: "/placeholder.svg",
    store: stores[3],
    foodWasteSaved: 1.0,
  },
  {
    id: "prod-12",
    name: "Nasi Goreng Spesial",
    description: "Nasi goreng dengan telur, ayam suwir, dan kerupuk",
    originalPrice: 28000,
    discountedPrice: 11200,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 7,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-14",
    weight: 450,
    image: "/placeholder.svg",
    store: stores[1],
    foodWasteSaved: 0.45,
  },
  {
    id: "prod-13",
    name: "Roti Sobek Keju",
    description: "Roti sobek lembut dengan taburan keju melimpah",
    originalPrice: 35000,
    discountedPrice: 14000,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 4,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-13",
    weight: 400,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.4,
  },
  {
    id: "prod-14",
    name: "Kangkung Hidroponik",
    description: "Kangkung hidroponik bersih tanpa pestisida",
    originalPrice: 12000,
    discountedPrice: 4800,
    discountPercentage: 60,
    category: "bahan-makanan",
    status: "layak-konsumsi",
    stock: 15,
    expiryDate: "2025-12-17",
    productionDate: "2025-12-14",
    weight: 200,
    image: "/placeholder.svg",
    store: stores[3],
    foodWasteSaved: 0.2,
  },
  {
    id: "prod-15",
    name: "Sisa Roti Tawar (Untuk Ternak)",
    description: "Roti tawar sisa produksi 3 hari lalu, cocok untuk pakan ternak",
    originalPrice: 15000,
    discountedPrice: 3000,
    discountPercentage: 80,
    category: "bahan-makanan",
    status: "untuk-ternak",
    stock: 25,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-11",
    weight: 800,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.8,
  },
  {
    id: "prod-16",
    name: "Sayur Kubis Luaran (Untuk Ternak)",
    description: "Daun kubis bagian luar yang masih segar, cocok untuk pakan ternak",
    originalPrice: 8000,
    discountedPrice: 2000,
    discountPercentage: 75,
    category: "bahan-makanan",
    status: "untuk-ternak",
    stock: 35,
    expiryDate: "2025-12-18",
    productionDate: "2025-12-13",
    weight: 1000,
    image: "/placeholder.svg",
    store: stores[3],
    foodWasteSaved: 1.0,
  },
  {
    id: "prod-17",
    name: "Puding Coklat Cup",
    description: "Puding coklat dalam cup plastik, dingin dan lezat",
    originalPrice: 12000,
    discountedPrice: 4800,
    discountPercentage: 60,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 9,
    expiryDate: "2025-12-16",
    productionDate: "2025-12-14",
    weight: 150,
    image: "/placeholder.svg",
    store: stores[0],
    foodWasteSaved: 0.15,
  },
  {
    id: "prod-18",
    name: "Salad Sayur Fresh",
    description: "Salad sayur segar dengan dressing thousand island terpisah",
    originalPrice: 35000,
    discountedPrice: 17500,
    discountPercentage: 50,
    category: "makanan-jadi",
    status: "layak-konsumsi",
    stock: 6,
    expiryDate: "2025-12-15",
    productionDate: "2025-12-14",
    weight: 300,
    image: "/placeholder.svg",
    store: stores[2],
    foodWasteSaved: 0.3,
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}

export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString("id-ID", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
}

export function getDaysUntilExpiry(expiryDate: string): number {
  const today = new Date()
  const expiry = new Date(expiryDate)
  const diffTime = expiry.getTime() - today.getTime()
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
}
