export const foodRescueSpots = [
  {
    id: 1,
    name: 'Bakery Aroma Tembalang',
    category: 'Roti & Kue',
    address: 'Jl. Ngesrep Timur V, Tembalang (Dekat Undip)',
    lat: -7.0495,
    lng: 110.4375,
    items: 'Mystery Box Roti Manis & Donat (Sisa produksi hari ini)',
    status: 'Layak Makan',
    price: 'Diskon 50%',
  },
  {
    id: 2,
    name: 'Catering Bu Tini Simpang Lima',
    category: 'Nasi Kotak',
    address: 'Area Belakang Matahari Simpang Lima',
    lat: -6.9904,
    lng: 110.4233,
    items: '20 Porsi Nasi Ayam Bakar (Kelebihan pesanan event)',
    status: 'Sangat Segar',
    price: 'Rp 10.000/porsi',
  },
  {
    id: 3,
    name: 'Gudang Buah Pasar Peterongan',
    category: 'Buah & Sayur',
    address: 'Jl. MT. Haryono, Pasar Peterongan',
    lat: -7.005,
    lng: 110.435,
    items: 'Pisang & Pepaya Overripe (Cocok buat smoothies/kue)',
    status: 'Matang Sekali',
    price: 'Rp 5.000/kg',
  },
  {
    id: 4,
    name: 'Supermarket Daily Setiabudi',
    category: 'Groceries',
    address: 'Jl. Setiabudi, Banyumanik',
    lat: -7.06,
    lng: 110.415,
    items: 'Yoghurt & Susu UHT (Exp H-3 Hari)',
    status: 'Near Expiry',
    price: 'Beli 1 Gratis 1',
  },
  {
    id: 5,
    name: 'Cafe Senja Kota Lama',
    category: 'Ampas Kopi',
    address: 'Jl. Letjen Suprapto, Kota Lama',
    lat: -6.9683,
    lng: 110.4272,
    items: 'Ampas Kopi (Coffee Grounds) 5kg',
    status: 'Limbah Organik',
    price: 'GRATIS (Ambil Sendiri)',
  },
  {
    id: 6,
    name: 'Warung Sembako Bu Sri',
    category: 'Bahan Masak',
    address: 'Jl. Pamularsih Raya, Semarang Barat',
    lat: -6.985,
    lng: 110.395,
    items: 'Telur Retak Cangkang (Isi aman)',
    status: 'Reject Fisik',
    price: 'Diskon 40%',
  },
  {
    id: 7,
    name: 'Dapur Hotel Pemuda',
    category: 'Buffet',
    address: 'Jl. Pemuda, Sekayu (Dekat Paragon)',
    lat: -6.98,
    lng: 110.418,
    items: 'Sisa Buffet Breakfast (Roti, Sereal, Buah Potong)',
    status: 'Layak Makan',
    price: 'Happy Hour 10.00 - 11.00',
  },
  {
    id: 8,
    name: 'Home Industry Keripik Gayamsari',
    category: 'Snack',
    address: 'Jl. Majapahit, Gayamsari',
    lat: -6.995,
    lng: 110.45,
    items: 'Remahan Keripik Singkong (Patahan)',
    status: 'Reject Bentuk',
    price: 'Rp 15.000/bal besar',
  },
]
